/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteCollectionsRouteImport } from './routes/_site.collections'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCraftsmanshipRouteImport } from './routes/_site.craftsmanship'
import { Route as SiteLookbookRouteImport } from './routes/_site.lookbook'
import { Route as SiteWishlistRouteImport } from './routes/_site.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminLookbookRouteImport } from './routes/admin.lookbook'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminPreviewRouteImport } from './routes/admin_.preview'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as SiteJewelleryIndexRouteImport } from './routes/_site.jewellery.index'
import { Route as SiteJewellerySlugRouteImport } from './routes/_site.jewellery.$slug'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin.collections.index'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin.collections.$id'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'
import { Route as AdminEnquiriesIndexRouteImport } from './routes/admin.enquiries.index'
import { Route as AdminEnquiriesIdRouteImport } from './routes/admin.enquiries.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCollectionsRoute = SiteCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCraftsmanshipRoute = SiteCraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLookbookRoute = SiteLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWishlistRoute = SiteWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLookbookRoute = AdminLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin_/preview',
  path: '/admin/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteJewelleryIndexRoute = SiteJewelleryIndexRouteImport.update({
  id: '/jewellery/',
  path: '/jewellery/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJewellerySlugRoute = SiteJewellerySlugRouteImport.update({
  id: '/jewellery/$slug',
  path: '/jewellery/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesIndexRoute = AdminEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesIdRoute = AdminEnquiriesIdRouteImport.update({
  id: '/enquiries/$id',
  path: '/enquiries/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/collections': typeof SiteCollectionsRoute
  '/contact': typeof SiteContactRoute
  '/craftsmanship': typeof SiteCraftsmanshipRoute
  '/lookbook': typeof SiteLookbookRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/jewellery/$slug': typeof SiteJewellerySlugRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/jewellery/': typeof SiteJewelleryIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/collections': typeof SiteCollectionsRoute
  '/contact': typeof SiteContactRoute
  '/craftsmanship': typeof SiteCraftsmanshipRoute
  '/lookbook': typeof SiteLookbookRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/jewellery/$slug': typeof SiteJewellerySlugRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/jewellery': typeof SiteJewelleryIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/enquiries': typeof AdminEnquiriesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/collections': typeof SiteCollectionsRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/craftsmanship': typeof SiteCraftsmanshipRoute
  '/_site/lookbook': typeof SiteLookbookRoute
  '/_site/wishlist': typeof SiteWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/preview': typeof AdminPreviewRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/jewellery/$slug': typeof SiteJewellerySlugRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/_site/jewellery/': typeof SiteJewelleryIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/collections'
    | '/contact'
    | '/craftsmanship'
    | '/lookbook'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/lookbook'
    | '/admin/media'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/login'
    | '/admin/preview'
    | '/admin/reset-password'
    | '/admin/'
    | '/jewellery/$slug'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/enquiries/$id'
    | '/admin/products/new'
    | '/jewellery/'
    | '/admin/collections/'
    | '/admin/enquiries/'
    | '/admin/products/'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/collections'
    | '/contact'
    | '/craftsmanship'
    | '/lookbook'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/lookbook'
    | '/admin/media'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/login'
    | '/admin/preview'
    | '/admin/reset-password'
    | '/'
    | '/admin'
    | '/jewellery/$slug'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/enquiries/$id'
    | '/admin/products/new'
    | '/jewellery'
    | '/admin/collections'
    | '/admin/enquiries'
    | '/admin/products'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/collections'
    | '/_site/contact'
    | '/_site/craftsmanship'
    | '/_site/lookbook'
    | '/_site/wishlist'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/lookbook'
    | '/admin/media'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin_/login'
    | '/admin_/preview'
    | '/admin_/reset-password'
    | '/_site/'
    | '/admin/'
    | '/_site/jewellery/$slug'
    | '/admin/collections/$id'
    | '/admin/collections/new'
    | '/admin/enquiries/$id'
    | '/admin/products/new'
    | '/_site/jewellery/'
    | '/admin/collections/'
    | '/admin/enquiries/'
    | '/admin/products/'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/collections': {
      id: '/_site/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof SiteCollectionsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/craftsmanship': {
      id: '/_site/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof SiteCraftsmanshipRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lookbook': {
      id: '/_site/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof SiteLookbookRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wishlist': {
      id: '/_site/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof SiteWishlistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lookbook': {
      id: '/admin/lookbook'
      path: '/lookbook'
      fullPath: '/admin/lookbook'
      preLoaderRoute: typeof AdminLookbookRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/preview': {
      id: '/admin_/preview'
      path: '/admin/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/jewellery/': {
      id: '/_site/jewellery/'
      path: '/jewellery'
      fullPath: '/jewellery/'
      preLoaderRoute: typeof SiteJewelleryIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/jewellery/$slug': {
      id: '/_site/jewellery/$slug'
      path: '/jewellery/$slug'
      fullPath: '/jewellery/$slug'
      preLoaderRoute: typeof SiteJewellerySlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/collections/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries/': {
      id: '/admin/enquiries/'
      path: '/enquiries'
      fullPath: '/admin/enquiries/'
      preLoaderRoute: typeof AdminEnquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries/$id': {
      id: '/admin/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminEnquiriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCollectionsRoute: typeof SiteCollectionsRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCraftsmanshipRoute: typeof SiteCraftsmanshipRoute
  SiteLookbookRoute: typeof SiteLookbookRoute
  SiteWishlistRoute: typeof SiteWishlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteJewellerySlugRoute: typeof SiteJewellerySlugRoute
  SiteJewelleryIndexRoute: typeof SiteJewelleryIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCollectionsRoute: SiteCollectionsRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCraftsmanshipRoute: SiteCraftsmanshipRoute,
  SiteLookbookRoute: SiteLookbookRoute,
  SiteWishlistRoute: SiteWishlistRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteJewellerySlugRoute: SiteJewellerySlugRoute,
  SiteJewelleryIndexRoute: SiteJewelleryIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminLookbookRoute: typeof AdminLookbookRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminEnquiriesIdRoute: typeof AdminEnquiriesIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminEnquiriesIndexRoute: typeof AdminEnquiriesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminLookbookRoute: AdminLookbookRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminEnquiriesIdRoute: AdminEnquiriesIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminEnquiriesIndexRoute: AdminEnquiriesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
